# Copyright (c) 2021 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Update copyright years

on:
    push:
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

jobs:
  update-copyright-years:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0 # No shallow clone, we need all history!
        - name: Update copyright years
          run: scripts/helpers/check_copyright_years.sh -c
        - name: Add uncommitted changes
          run: |
            git add .
            git commit -m "Auto fixing copyright years"
        - name: Fix upstream
          run:  |
            git remote set-url origin https://x-access-token:$COMMITTER_TOKEN@github.com/$GITHUB_REPOSITORY.git
            git config --global user.email "$USER_EMAIL"
            git config --global user.name "$USER_NAME"
          env:
            COMMITTER_TOKEN: ${{ secrets.MATTER_PAT }}
            USER_EMAIL: ${{ secrets.MATTER_PAT_EMAIL }}
            USER_NAME: ${{ secrets.MATTER_PAT_NAME }}
            GITHUB_REPOSITORY: ${{ github.GITHUB_REPOSITORY }}
        - name: Push
          run: git push
